create sequence hibernate_sequence start 1 increment 1;
drop table if exists customer CASCADE;

create table customer (
    id int8 generated by default as identity,
    created int8,
    email varchar(255),
    full_name varchar(255),
    is_active boolean not null,
    phone varchar(255),
    updated int8,
    primary key (id)
);