drop table if exists customer CASCADE;

create table customer (
    id bigint generated by default as identity,
    created bigint,
    email varchar(255),
    full_name varchar(255),
    is_active boolean not null,
    phone varchar(255),
    updated bigint,
    primary key (id)
);